name: link_five
description: A game. First to get five in a row wins!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.4+4

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.12.1
  built_collection: ^5.1.0
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10

dev_dependencies:
  build_runner: ^2.10.4
  built_value_generator: ^8.12.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
